app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/',include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/',include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, MarcaView, MarcaNew, MarcaEdit, marca_inactivar, UMView, UMEdit, UMNew, UMEdit, um_inactivar, ProductoView, ProductoNew, ProductoEdit, producto_inactivar

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new/', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),
    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new/', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'), 
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),
    path('marcas/', MarcaView.as_view(), name='marca_list'),
    path('marcas/new/', MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/inactivar/<int:id>', marca_inactivar, name='marca_inactivar'),
    path('unidades/', UMView.as_view(), name='um_list'),
    path('unidades/new/', UMNew.as_view(), name='um_new'  ),
    path('unidades/edit/<int:pk>',UMEdit.as_view(), name='um_edit'),
    path('unidades/inactivar/<int:id>',um_inactivar, name='um_inactivar'),
    path('productos/', ProductoView.as_view(), name='producto_list'),
    path('productos/new/', ProductoNew.as_view(), name='producto_new'  ),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:id>',producto_inactivar, name='producto_inactivar'),


]

bases/models.py
from django.db import models
from django.contrib.auth.models import User


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True, null=True)


    class Meta:
        abstract=True

inv/models.py
from django.db import models

from bases.models import ClaseModelo

# Create your models here.

class Categoria(ClaseModelo):
    
    descripcion = models.CharField(
        max_length = 100,
        help_text = 'Descripcion de la categoria',
        unique = True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    
    class Meta:
        verbose_name_plural = "Categorias"


class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length = 100,
        help_text = 'Descripcion de la subcategoria'
    )

    def __str__(self):
        return '{} : {}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()


    class Meta:
        verbose_name_plural = "SubCategorias"
        unique_together = ('categoria', 'descripcion')


class Marca(ClaseModelo):
    
    descripcion = models.CharField(
        max_length = 100,
        help_text = 'Descripcion de la marca',
        unique = True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    
    class Meta:
        verbose_name_plural = "Marcas" 


class UnidadesMedidas(ClaseModelo):

    descripcion = models.CharField(
        max_length = 100,
        help_text = 'Descripcion de la Unidad de Medida',
        unique = True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadesMedidas, self).save()

    class Meta:
        verbose_name_plural = 'Unidades de medida' 


class Producto(ClaseModelo):

    codigo = models.CharField(
        max_length=20,
        unique=False
    )
    
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadesMedidas, on_delete=models.CASCADE )
    sub_categoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE )


    def __str__(self):
        return '{}'.format(self.descripcion)

    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    
    class Meta:
        verbose_name_plural = "Productos" 
        unique_together = ('codigo', 'codigo_barra')

inv/forms.py
from django import forms

from .models import Categoria, SubCategoria, Marca, UnidadesMedidas, Producto



class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion' : 'Descripcion de la categoria', 
                    'estado' : 'Estado' }
        widget = { 'descripcion' : forms.TextInput }        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset= Categoria.objects.filter(estado = True)
        .order_by('descripcion')
    );
    class Meta:
        model = SubCategoria
        fields = ['categoria','descripcion', 'estado']
        labels = {'descripcion' : 'Sub Categoria', 
                    'estado' : 'Estado' }
        widget = { 'descripcion' : forms.TextInput }        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

        self.fields['categoria'].empty_label = 'Seleccione Categoria'
        

class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['descripcion', 'estado']
        labels = {'descripcion' : 'Descripcion de la marca', 
                    'estado' : 'Estado' }
        widget = { 'descripcion' : forms.TextInput }        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })



class UMForm(forms.ModelForm):

    class Meta:
        model = UnidadesMedidas
        fields = ['descripcion', 'estado']
        label = { 'descripcion' : 'Descripcion Unidad de Medida', 
                    'estado' : 'Estado'}
        
        widget = { 'descripcion' : forms.TextInput }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class' : 'form-control'
                })


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo', 'codigo_barra', 'descripcion', 'estado',
                    'precio', 'existencia', 'ultima_compra', 'marca', 'sub_categoria',
                    'unidad_medida']
        exclude = ['um', 'fm', 'uc', 'fc']
        widget = {'descripcion' : forms.TextInput()}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class' : 'form-control'
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True  

                            

inv/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect, render

from .models import Categoria, SubCategoria, Marca, UnidadesMedidas, Producto
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UMForm, ProductoForm

class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = "bases:login"


class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url=reverse_lazy("inv:categoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url=reverse_lazy("inv:categoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)        


class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = Categoria
    template_name = "inv/catalogos_del.html"
    context_object_name = "obj"
    success_url=reverse_lazy("inv:categoria_list")


class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model = SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = "bases:login"

class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url=reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url=reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
        
class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = SubCategoria
    template_name = "inv/catalogos_del.html"
    context_object_name = "obj"
    success_url=reverse_lazy("inv:subcategoria_list")        


class MarcaView(LoginRequiredMixin, generic.ListView):
    model = Marca
    template_name = "inv/marca_list.html"
    context_object_name = "obj"
    login_url = "bases:login"


class MarcaNew(LoginRequiredMixin, generic.CreateView):
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url=reverse_lazy("inv:marca_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class MarcaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:marca_list")
    login_url = "bases:login"


    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


def marca_inactivar(request, id):
    marca = Marca.objects.filter(pk=id).first()
    contexto = {}
    template_name = "inv/catalogos_del.html"

    if not marca:
        return redirect("inv:marca_list")

    if request.method == 'GET':
        contexto = {'obj' : marca}

    if request.method == 'POST':
        marca.estado = False
        marca.save()
        return redirect("inv:marca_list")

    
    return render(request, template_name, contexto)



class UMView(LoginRequiredMixin, generic.ListView):
    model = UnidadesMedidas
    template_name = 'inv/um_list.html'
    context_object_name = 'obj'
    login_url = "bases:login"

class UMNew(LoginRequiredMixin, generic.CreateView):
    model = UnidadesMedidas
    template_name = 'inv/um_form.html'
    context_object_name = 'obj'
    login_url = 'bases:login'
    form_class = UMForm
    success_url = reverse_lazy('inv:um_list')

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)




class UMEdit(LoginRequiredMixin, generic.UpdateView):
    model = UnidadesMedidas
    template_name = 'inv/um_form.html'
    context_object_name = 'obj'
    login_url = 'bases:login'
    form_class = UMForm
    success_url = reverse_lazy('inv:um_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


def um_inactivar(request, id):
    um = UnidadesMedidas.objects.filter(pk=id).first()
    contexto = {}
    template_name = "inv/catalogos_del.html"

    if not um:
        return redirect("inv:um_list")

    if request.method == 'GET':
        contexto = {'obj' : um}

    if request.method == 'POST':
        um.estado = False
        um.save()
        return redirect("inv:um_list")

    
    return render(request, template_name, contexto)        


class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = 'inv/producto_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'


class ProductoNew(LoginRequiredMixin, generic.CreateView):
    model = Producto
    template_name = 'inv/producto_form.html'
    context_object_name = 'obj'
    login_url = 'bases:login'
    form_class = ProductoForm
    success_url = reverse_lazy('inv:producto_list')

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    model = Producto
    template_name = 'inv/producto_form.html'
    context_object_name = 'obj'
    login_url = 'bases:login'
    form_class = ProductoForm
    success_url = reverse_lazy('inv:producto_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)



def producto_inactivar(request, id):
    prod = Producto.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'inv/catalogos_del.html'

    if not prod:
        return redirect('inv:producto_list')

    if request.method == 'GET':
        contexto = {'obj':prod}
        return render(request, template_name, contexto)

    if request.method == 'POST':
        prod.estado = False
        prod.save()
        return redirect('inv:producto_list') 

inv/templates/inv/categoria_form.html
{% extends 'base/base.html' %} {% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">

            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">

                    <div class="row no-gutters align-items-center">

                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %}Nueva {% endif %} categoria
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-10">
                                    <div class="input-group">
                                        <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion" value=" {% if obj %} {{ obj.descripcion }} {% endif %}">
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="input-group">
                                        <label for="id_estado">Estado</label>
                                        <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %}>
                                    </div>
                                </div>
                                <!-- {{ form.as_p }} -->
                            </div>


                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> {% if obj %} Actualizar {% else %} Guardar {% endif %}</button>
                                    <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"> <span class="fa fa-undo"></span> Cancelar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>

{% endblock %} {% block js_page %} {% endblock %}

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %} {% block page_content %}



<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"> <i class="far fa-calendar-plus"></i> Nueva</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">
            No hay categorias
        </div>
        {% else %}

        <table class="table table-striped table-hover">
            <thead>
                <th>ID</th>
                <th>Descripcion</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>F. Modif.</th>
                <th class="all">Acciones</th>
            </thead>

            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.estado| yesno:"Activo,Inactivo" }}</td>
                    <td>{{ item.fc | date:"d/m/Y H:i:s" }}</td>
                    <td>{{ item.fm | date:"d/m/Y H:i:s" }}</td>
                    <td>
                        <a href="{% url 'inv:categoria_edit'  item.id %}" class="btn btn-warning btn-circle" role="button"> <i class="far fa-edit"></i> </a>
                        <a href="{% url 'inv:categoria_del'  item.id %}" class="btn btn-danger btn-circle" role="button"> <i class="far fa-trash-alt"></i> </a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}
    </div>
</div>




{% endblock %} {% block js_page %}
<script>
    // call datatable jquery plugin
    $(document).ready(function() {
        $('.table').DataTable();
    });
</script>




{% endblock %}

inv/templates/inv/producto_list.html
{% extends 'base/base.html' %} {% block page_content %}



<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" onclick="return abrir_modal('{% url 'inv:producto_new' %}')" href="#"> <i class="far fa-calendar-plus"></i> Nuevo</a>

            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">
            No hay productos
        </div>
        {% else %}

        <table class="table table-striped table-hover">
            <thead>
                <th>Sub. Cat</th>
                <th>Codigo</th>
                <th>Barra</th>
                <th>Descripcion</th>
                <th>Existencia</th>
                <th>Marca</th>
                <th>U.M</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>

            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.sub_categoria }}</td>
                    <td>{{ item.codigo }}</td>
                    <td>{{ item.codigo_barra }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.existencia }}</td>
                    <td>{{ item.marca }}</td>
                    <td>{{ item.unidad_medida }}</td>
                    <td>{{ item.estado| yesno:"Activo,Inactivo" }}</td>
                    <td>
                        <!-- <a href="{% url 'inv:producto_edit'  item.id %}" class="btn btn-warning btn-circle" role="button"> <i class="far fa-edit"></i> </a> -->
                        <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'inv:producto_edit' item.id %}')"> <i class="far fa-edit"></i>  </button>

                        <a href="{% url 'inv:producto_inactivar'  item.id %}" class="btn btn-danger btn-circle" role="button"> <i class="far fa-thumbs-down"></i> </a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}
    </div>
</div>




{% endblock %} {% block js_page %}
<script>
    // call datatable jquery plugin
    $(document).ready(function() {
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "mostrar _MENU_ registros",

            }
        });
    });
</script>




{% endblock %}

inv/templates/inv/subcategoria_list.html
{% extends 'base/base.html' %} {% block page_content %}



<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorias</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"> <i class="far fa-calendar-plus"></i> Nueva</a>

            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">
            No hay Sub Categorias
        </div>
        {% else %}

        <table class="table table-striped table-hover">
            <thead>
                <th>Categoria</th>
                <th>ID</th>
                <th>Descripcion</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>F. Modif.</th>
                <th class="all">Acciones</th>
            </thead>

            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.categoria }}</td>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.estado| yesno:"Activo,Inactivo" }}</td>
                    <td>{{ item.fc | date:"d/m/Y H:i:s" }}</td>
                    <td>{{ item.fm | date:"d/m/Y H:i:s" }}</td>
                    <td>
                        <a href="{% url 'inv:categoria_edit'  item.id %}" class="btn btn-warning btn-circle" role="button"> <i class="far fa-edit"></i> </a>
                        <a href="{% url 'inv:categoria_del'  item.id %}" class="btn btn-danger btn-circle" role="button"> <i class="far fa-trash-alt"></i> </a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}
    </div>
</div>




{% endblock %} {% block js_page %}
<script>
    // call datatable jquery plugin
    $(document).ready(function() {
        $('.table').DataTable();
    });
</script>




{% endblock %}

inv/templates/inv/um_list.html
{% extends 'base/base.html' %} {% block page_content %}



<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Unidades de medidas</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'inv:um_new' %}"> <i class="far fa-calendar-plus"></i> Nueva</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">
            No hay unidades de medidas
        </div>
        {% else %}

        <table class="table table-striped table-hover">
            <thead>
                <th>ID</th>
                <th>Descripcion</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>F. Modif.</th>
                <th class="all">Acciones</th>
            </thead>

            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.estado| yesno:"Activo,Inactivo" }}</td>
                    <td>{{ item.fc | date:"d/m/Y H:i:s" }}</td>
                    <td>{{ item.fm | date:"d/m/Y H:i:s" }}</td>
                    <td>
                        <a href="{% url 'inv:um_edit' item.id %}" class="btn btn-warning btn-circle" role="button"> <i class="far fa-edit"></i> </a>
                        <a href="{% url 'inv:um_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"> <i class="far fa-thumbs-down"></i> </a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}
    </div>
</div>




{% endblock %} {% block js_page %}
<script>
    // call datatable jquery plugin
    $(document).ready(function() {
        $('.table').DataTable();
    });
</script>




{% endblock %}